// This file is auto-generated by makes-code ... do not edit

package types

import (
	"go.mongodb.org/mongo-driver/bson"
)

type UserDocumentPartials []*UserDocumentPartial

type UserDocumentPartial struct {
	userData
}

type userDocumentPartial struct {
	ID   string `bson:"_id"`
	Name string `bson:"n"`
}

func ToUserDocumentPartial(u User) *UserDocumentPartial {
	return &UserDocumentPartial{userData{
		id:   u.ID(),
		name: u.Name(),
	}}
}

func (u UserDocumentPartial) MarshalBSON() ([]byte, error) {
	return bson.Marshal(userDocumentPartial{
		ID:   u.id,
		Name: u.name,
	})
}

func (u *UserDocumentPartial) UnmarshalBSON(data []byte) error {
	var tmp userDocumentPartial
	if err := bson.Unmarshal(data, &tmp); err != nil {
		return err
	}

	u.userData = userData{
		id:   tmp.ID,
		name: tmp.Name,
	}
	return nil
}

func ToUserDocumentPartials(users Users) UserDocumentPartials {
	docs := make(UserDocumentPartials, len(users))
	for i, user := range users {
		docs[i] = ToUserDocumentPartial(user)
	}
	return docs
}

func (docs UserDocumentPartials) Users() Users {
	users := make(Users, len(docs))
	for i, doc := range docs {
		users[i] = doc
	}
	return users
}
