package command

import (
	"flag"
	"fmt"
	"strings"

	"github.com/makes-code/gen/internal/cli"
	"github.com/makes-code/gen/internal/inspect"
	"github.com/makes-code/gen/internal/utils"

	mcli "github.com/mitchellh/cli"
)

type typePayloadInputs struct {
	tag     string
	include utils.StringArray
	exclude utils.StringArray
	strict  bool
}

func TypePayload() (mcli.Command, error) {
	var inputs typePayloadInputs

	return &cli.CmdCodegen{
		CmdMeta: cli.CmdMeta{
			Name:     "payload",
			Help:     "Generate a payload model",
			Synopsis: "Generate a payload model",
		},
		FileName: func(systemName string) string {
			var suffix string
			if inputs.tag != "" {
				suffix = "_" + strings.ToLower(inputs.tag)
			}
			return fmt.Sprintf("%s_gen_payload%s.go", systemName, suffix)
		},
		Flags: func(fs *flag.FlagSet) {
			fs.StringVar(&inputs.tag, "tag", "", "")
			fs.Var(&inputs.include, "i", "")
			fs.Var(&inputs.exclude, "x", "")
			fs.BoolVar(&inputs.strict, "strict", false, "")
		},
		Runner: func(data inspect.Data) (string, interface{}, error) {
			whitelist := map[string]string{}
			for _, f := range inputs.include {
				name := f
				var nameOverride string

				if strings.Contains(f, "=") {
					parts := strings.Split(f, "=")
					name, nameOverride = parts[0], parts[1]
				}

				whitelist[name] = nameOverride
			}

			blacklist := map[string]struct{}{}
			for _, f := range inputs.exclude {
				blacklist[f] = struct{}{}
			}

			var fields []inspect.Field
			for _, field := range data.Fields {
				if _, ok := blacklist[field.Names.Public]; ok {
					continue
				}

				nameOverride, ok := whitelist[field.Names.Public]
				if !ok && inputs.strict {
					continue
				}
				if nameOverride != "" {
					field.Names.Field = nameOverride
				}

				fields = append(fields, field)
			}

			imports := data.Imports.New()
			imports.Use("json", `"encoding/json"`)
			for _, field := range fields {
				imports.Include(field.Type.Imports()...)
			}

			return tmplPayload, tmplDataPayload{
				Data: inspect.Data{
					Pkg:     data.Pkg,
					Names:   data.Names,
					Fields:  fields,
					Imports: imports,
				},
				Tag: inputs.tag,
			}, nil
		},
	}, nil
}

type tmplDataPayload struct {
	inspect.Data
	Tag string
}

var tmplPayload = `
{{$ := .Names}}
// This file is auto-generated by makes-code ... do not edit

package {{.Pkg}}

{{if not .Imports.Empty}}
import ({{range .Imports.Groups}}
{{range .}}  {{.}}
{{end -}}
{{end}})
{{end}}

type {{$.Public}}Payload{{.Tag}}s []*{{$.Public}}Payload{{.Tag}}

type {{$.Public}}Payload{{.Tag}} struct {
	{{$.Private}}Data
}

type {{$.Private}}Payload{{.Tag}} struct {
{{range .Fields}} {{.Names.Public}} {{.Type}} {{.Tag "json"}}
{{end -}}
}

func To{{$.Public}}Payload{{.Tag}}({{$.Short}} {{$.Public}}) *{{$.Public}}Payload{{.Tag}} {
	return &{{$.Public}}Payload{{.Tag}}{{"{"}}{{$.Private}}Data{{"{"}}
{{range .Fields}}    {{.Names.Private}}: {{$.Short}}.{{.Names.Public}}(),
{{end -}}
	{{"}"}}{{"}"}}
}

func ({{$.Short}} {{$.Public}}Payload{{.Tag}}) MarshalJSON() ([]byte, error) {
	return json.Marshal({{$.Private}}Payload{{.Tag}}{
{{range .Fields}}    {{.Names.Public}}: {{$.Short}}.{{.Names.Private}},
{{end -}}
	})
}

func ({{$.Short}} *{{$.Public}}Payload{{.Tag}}) UnmarshalJSON(data []byte) error {
	var tmp {{$.Private}}Payload{{.Tag}}
	if err := json.Unmarshal(data, &tmp); err != nil {
		return err
	}

	{{$.Short}}.{{$.Private}}Data = {{$.Private}}Data{
{{range .Fields}}    {{.Names.Private}}: tmp.{{.Names.Public}},
{{end -}}
	}
	return nil
}

func To{{$.Public}}Payload{{.Tag}}s({{$.Private}}s {{$.Public}}s) {{$.Public}}Payload{{.Tag}}s {
  docs := make({{$.Public}}Payload{{.Tag}}s, len({{$.Private}}s))
	for i, {{$.Private}} := range {{$.Private}}s {
		docs[i] = To{{$.Public}}Payload{{.Tag}}({{$.Private}})
	}
	return docs
}

func (docs {{$.Public}}Payload{{.Tag}}s) {{$.Public}}s() {{$.Public}}s {
	{{$.Private}}s := make({{$.Public}}s, len(docs))
	for i, doc := range docs {
		{{$.Private}}s[i] = doc
	}
	return {{$.Private}}s
}
`
